kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-org2-peer0-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: example-org2-peer0-files