kind: PersistentVolume
apiVersion: v1
metadata:
  name: example-org2-peer0-pv
  labels:
    type: local
    name: example-org2-peer0-files
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/example-org2-peer0/var
    server: storage.local.parisi.biz
    readOnly: false