apiVersion: v1
kind: Service
metadata:
  name: example-org4-ca
  labels:
    run: example-org4-ca
spec:
  type: NodePort
  selector:
    app: example-org4-ca
  ports:
    - protocol: TCP
      nodePort: 30354
      targetPort: 10054
      port: 30354
      name: grpc
    # - protocol: TCP
    #  port: 7054
    #  name: grpc1