apiVersion: v1
kind: Service
metadata:
  name: example-orderer
  labels:
    run: example-orderer
spec:
  type: NodePort
  selector:
    name: example-orderer
  ports:
    - protocol: TCP
      nodePort: 31010
      targetPort: 31010
      port: 31010
      name: grpc