apiVersion: v1
kind: Service
metadata:
  name: example-org1-ca
  labels:
    run: example-org1-ca
spec:
  type: NodePort
  selector:
    app: example-org1-ca
  ports:
    - protocol: TCP
      nodePort: 30054
      targetPort: 7054
      port: 30054
      name: grpc
    # - protocol: TCP
    #  port: 7054
    #  name: grpc1