apiVersion: v1
kind: Service
metadata:
  name: example-org4-peer0
  labels:
    run: example-org4-peer0
spec:
  type: NodePort
  selector:
    name: example-org4-peer0
  ports:
    - protocol: TCP
      nodePort: 30410
      targetPort: 30410
      port: 30410
      name: grpc
    - protocol: TCP
      nodePort: 30411
      targetPort: 30411
      port: 30411
      name: events