apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-org1-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-org1-ca
  template:
    metadata:
      labels:
        app: example-org1-ca
    spec:
      volumes:
        - name: fabric-example-files
          persistentVolumeClaim:
            claimName: fabric-example-pvc
      containers:
        - name: exampleorg1-ca
          image: hyperledger/fabric-ca:1.4.4
          imagePullPolicy: IfNotPresent
          command:
            [
          		'sh',
          		'-c',
              'fabric-ca-server start -b admin:adminpw -d'
            ]
          env:
            - name: TZ
              value: 'America/Sao_Paulo'
            - name: FABRIC_CA_SERVER_CA_NAME
              value: 'ca.org1.example.com'
            - name: FABRIC_CA_SERVER_DEBUG
              value: 'true'
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: 'false'
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /fabric/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /fabric/crypto-config/peerOrganizations/org1.example.com/ca/4fc404f8c78b86d233f687878600ba1f9a5c72f9d3bf5d998dcce0ea3d14d91c_sk
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: /fabric/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: /fabric/crypto-config/peerOrganizations/org1.example.com/ca/4fc404f8c78b86d233f687878600ba1f9a5c72f9d3bf5d998dcce0ea3d14d91c_sk
            - name: GODEBUG
              value: 'netdns=go'
          volumeMounts:
            - mountPath: /fabric
              name: fabric-example-files
