apiVersion: v1
kind: Service
metadata:
  name: example-org2-ca
  labels:
    run: example-org2-ca
spec:
  type: NodePort
  selector:
    app: example-org2-ca
  ports:
    - protocol: TCP
      nodePort: 30154
      targetPort: 8054
      port: 30154
      name: grpc
    # - protocol: TCP
    #  port: 7054
    #  name: grpc1