apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-org3-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-org3-ca
  template:
    metadata:
      labels:
        app: example-org3-ca
    spec:
      volumes:
        - name: fabric-example-files
          persistentVolumeClaim:
            claimName: fabric-example-pvc
      containers:
        - name: exampleorg3-ca
          image: hyperledger/fabric-ca:1.4.4
          imagePullPolicy: IfNotPresent
          command:
            [
          		'sh',
          		'-c',
              'fabric-ca-server start -b admin:adminpw -d'
            ]
          env:
            - name: TZ
              value: 'America/Sao_Paulo'
            - name: FABRIC_CA_SERVER_CA_NAME
              value: 'ca.org3.example.com'
            - name: FABRIC_CA_SERVER_DEBUG
              value: 'true'
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: 'false'
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /fabric/crypto-config/peerOrganizations/org3.example.com/ca/ca.org3.example.com-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /fabric/crypto-config/peerOrganizations/org3.example.com/ca/ecd5ceec52d807c1dc348badbb958c78ccfc4ff3d7c32c6a545436983b4f133d_sk
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: /fabric/crypto-config/peerOrganizations/org3.example.com/ca/ca.org3.example.com-cert.pem
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: /fabric/crypto-config/peerOrganizations/org3.example.com/ca/ecd5ceec52d807c1dc348badbb958c78ccfc4ff3d7c32c6a545436983b4f133d_sk
            - name: GODEBUG
              value: 'netdns=go'
          volumeMounts:
            - mountPath: /fabric
              name: fabric-example-files
