apiVersion: v1
kind: Service
metadata:
  name: example-org3-ca
  labels:
    run: example-org3-ca
spec:
  type: NodePort
  selector:
    app: example-org3-ca
  ports:
    - protocol: TCP
      nodePort: 30254
      targetPort: 9054
      port: 30254
      name: grpc
    # - protocol: TCP
    #  port: 7054
    #  name: grpc1