apiVersion: v1
kind: Service
metadata:
  name: example-org1-peer0
  labels:
    run: example-org1-peer0
spec:
  type: NodePort
  selector:
    name: example-org1-peer0
  ports:
    - protocol: TCP
      nodePort: 30110
      targetPort: 30110
      port: 30110
      name: grpc
    - protocol: TCP
      nodePort: 30111
      targetPort: 30111
      port: 30111
      name: events