apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-org2-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-org2-ca
  template:
    metadata:
      labels:
        app: example-org2-ca
    spec:
      volumes:
        - name: fabric-example-files
          persistentVolumeClaim:
            claimName: fabric-example-pvc
      containers:
        - name: exampleorg2-ca
          image: hyperledger/fabric-ca:1.4.4
          imagePullPolicy: IfNotPresent
          command:
            [
          		'sh',
          		'-c',
              'fabric-ca-server start -b admin:adminpw -d'
            ]
          env:
            - name: TZ
              value: 'America/Sao_Paulo'
            - name: FABRIC_CA_SERVER_CA_NAME
              value: 'ca.org2.example.com'
            - name: FABRIC_CA_SERVER_DEBUG
              value: 'true'
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: 'false'
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /fabric/crypto-config/peerOrganizations/org2.example.com/ca/ca.org2.example.com-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /fabric/crypto-config/peerOrganizations/org2.example.com/ca/3e555137f320759d7c557108a8759b281670845b2015c5aa8831b20409df6aeb_sk
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: /fabric/crypto-config/peerOrganizations/org2.example.com/ca/ca.org2.example.com-cert.pem
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: /fabric/crypto-config/peerOrganizations/org2.example.com/ca/3e555137f320759d7c557108a8759b281670845b2015c5aa8831b20409df6aeb_sk
            - name: GODEBUG
              value: 'netdns=go'
          volumeMounts:
            - mountPath: /fabric
              name: fabric-example-files
